export const gxMobileTokens = {
  bg: '#08090C',
  bgSoft: '#0E1015',
  surface: '#12151B',
  surfaceSoft: '#181C24',
  surfaceElevated: '#1F242E',
  textPrimary: '#F4F7FA',
  textSecondary: '#9CA3AF',
  textMuted: '#6B7280',
  textDisabled: '#4B5563',
  primary: '#B9F719',
  primaryStrong: '#D2FF1F',
  primarySoft: 'rgba(185, 247, 25, 0.12)',
  primaryBorder: 'rgba(185, 247, 25, 0.25)',
  primaryMuted: '#84A618',
  chatIncomingBg: '#141820',
  chatIncomingBorder: 'rgba(255, 255, 255, 0.08)',
  chatIncomingText: '#F4F7FA',
  chatOutgoingBg: '#182414',
  chatOutgoingBorder: 'rgba(185, 247, 25, 0.22)',
  chatOutgoingText: '#F4F7FA',
  chatOutgoingAccentBg: '#B9F719',
  chatOutgoingAccentText: '#08090C',
  success: '#22C55E',
  warning: '#F59E0B',
  error: '#EF4444',
  info: '#38BDF8',
  whiteBorderSubtle: 'rgba(255, 255, 255, 0.06)',
  whiteBorder: 'rgba(255, 255, 255, 0.10)',
} as const;

export const theme = {
  colors: {
    background: gxMobileTokens.bg,
    backgroundSoft: gxMobileTokens.bgSoft,
    surface: gxMobileTokens.surface,
    surfaceSoft: gxMobileTokens.surfaceSoft,
    surfaceRaised: gxMobileTokens.surfaceElevated,
    border: gxMobileTokens.whiteBorder,
    borderSubtle: gxMobileTokens.whiteBorderSubtle,
    text: gxMobileTokens.textPrimary,
    textSecondary: gxMobileTokens.textSecondary,
    mutedText: gxMobileTokens.textMuted,
    disabledText: gxMobileTokens.textDisabled,
    accent: gxMobileTokens.primary,
    accentStrong: gxMobileTokens.primaryStrong,
    accentSoft: gxMobileTokens.primarySoft,
    accentBorder: gxMobileTokens.primaryBorder,
    accentMuted: gxMobileTokens.primaryMuted,
    accentDark: gxMobileTokens.chatOutgoingBg,
    success: gxMobileTokens.success,
    danger: gxMobileTokens.error,
    warning: gxMobileTokens.warning,
    info: gxMobileTokens.info,
    chatIncomingBg: gxMobileTokens.chatIncomingBg,
    chatIncomingBorder: gxMobileTokens.chatIncomingBorder,
    chatIncomingText: gxMobileTokens.chatIncomingText,
    chatOutgoingBg: gxMobileTokens.chatOutgoingBg,
    chatOutgoingBorder: gxMobileTokens.chatOutgoingBorder,
    chatOutgoingText: gxMobileTokens.chatOutgoingText,
    chatOutgoingAccentBg: gxMobileTokens.chatOutgoingAccentBg,
    chatOutgoingAccentText: gxMobileTokens.chatOutgoingAccentText,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 40,
  },
  radius: {
    sm: 12,
    md: 18,
    lg: 22,
    pill: 999,
  },
  typography: {
    caption: 12,
    small: 14,
    body: 15,
    title: 24,
    section: 17,
    hero: 28,
  },
} as const;
