import type { MobileInboxAudience } from '@/src/types';

export const queryKeys = {
  token: ['auth', 'token'] as const,
  session: ['auth', 'session'] as const,
  subscription: (userId = 'anonymous', audience = 'UNKNOWN') => ['subscription', 'status', userId, audience] as const,
  packages: (userId = 'anonymous', audience = 'UNKNOWN') => ['packages', userId, audience] as const,
  profile: ['profile'] as const,
  chats: (audience: MobileInboxAudience, includeSupportData = false) => ['chats', audience, includeSupportData ? 'support' : 'list'] as const,
  chatThread: (conversationId: string, audience: MobileInboxAudience) => ['chat-thread', conversationId, audience] as const,
  projects: ['projects'] as const,
  projectDetail: (projectId: string) => ['project', projectId] as const,
  workMatching: ['work-matching'] as const,
  assignments: ['assignments'] as const,
  assignmentDetail: (assignmentId: string) => ['assignment', assignmentId] as const,
  services: ['services'] as const,
  serviceDetail: (serviceId: string) => ['service', serviceId] as const,
  orders: ['orders'] as const,
  notifications: ['notifications'] as const,
  onboarding: ['onboarding', 'progress'] as const,
  onboardingGate: (role: string, userId?: string) => userId ? ['onboarding', 'required-gate', role, userId] as const : ['onboarding', 'required-gate', role] as const,
  freelancerQualification: ['freelancer', 'qualification-onboarding'] as const,
  freelancerAvailability: ['freelancer', 'availability'] as const,
  roleDashboard: (role: string) => ['dashboard', role] as const,
  wallet: ['freelancer', 'wallet'] as const,
  paymentDetails: ['freelancer', 'payment-details'] as const,
  payoutRequests: ['freelancer', 'payout-requests'] as const,
  accountingRequests: (audience: 'agency' | 'editor') => ['accounting', 'requests', audience] as const,
  managers: ['admin', 'managers'] as const,
  teamRequests: ['freelancer', 'team-requests'] as const,
  editorDirectory: ['team', 'editor-directory'] as const,
  agencyDirectory: ['team', 'agency-directory'] as const,
  contacts: ['contacts'] as const,
  whatsappIntegration: ['integrations', 'whatsapp'] as const,
  upiConfig: ['integrations', 'upi'] as const,
  youtubeIntegration: ['integrations', 'youtube'] as const,
  pushConfig: ['integrations', 'push-config'] as const,
  pushDebug: ['integrations', 'push-debug'] as const,
  pushDeviceDiagnostics: ['integrations', 'push-device-diagnostics'] as const,
  systemHealth: ['system', 'db-health'] as const,
  mobileConfig: ['mobile-config'] as const,
  freelancerReferrals: ['freelancer', 'referrals'] as const,
};
